unless go_root = ENV["GOROOT"]
  puts "the $GOROOT env must be ste."
  exit
end

go_api_path = "#{go_root}/api/go1.txt"
unless api_text = File.read(go_api_path) rescue nil
  puts "could not read Go api from path: #{go_api_path}"
  exit
end

apis = {}
for definition in api_text.lines do
  # ignore api definitions similar to below:
  #   pkg archive/tar, type Header struct, Devmajor int64
  #   pkg go/ast, type Decl interface, End() token.Pos
  #   pkg go/build, var Default Context
  #   pkg syscall (windows-amd64), const SW_RESTORE ideal-int
  next if definition =~ /(.+\,.+(struct|interface)[\,|\:].+)|(var )|(syscall.+const )/

  definition = definition.          #=> pkg log/syslog (darwin-386), const LOG_ALERT Priority
                gsub("pkg ", "").   #=> log/syslog (darwin-386), const LOG_ALERT Priority
                gsub(", ", ": ").   #=> log/syslog (darwin-386): const LOG_ALERT Priority
                gsub(/ \([\w\-]+\)\:/, ":"). #=> log/syslog: const LOG_ALERT Priority
                strip

  name = definition.          #=> log/syslog: const LOG_ALERT Priority
          gsub(/^.+\//, "").  #=> syslog: const LOG_ALERT Priority
          gsub(": ", ".").    #=> syslog.const LOG_ALERT Priority
          gsub(/(const|func|method|type) /, ""). #=> syslog.LOG_ALERT Priority
          gsub(/ [\w\-]+?$/, ""). #=> syslog.LOG_ALERT
          # tar.(*Reader) Next() (*Header.error) => tar.Reader.Next
          gsub(/\.\(\*?/, ".").gsub(/\) /, ".").gsub(/ *\(.*$/, "").gsub(/ interface.+/, "")


  if name =~ /\.$/
    puts "Malformed name: #{name}"
  end

  pkg_name = name.split(".").first
  unless apis[name]
    apis[pkg_name] = "import \\\"#{definition.split(":").first}\\\""
  end

  apis[name] = definition
end

API_SEPARATOR = "#=================== generated by update.rb"
ruby_apis = <<-RUBY
#{API_SEPARATOR}
apis = [
#{apis.to_a.map{|a| "  [\"#{a[0]}\", \"#{a[1]}\"]"}.join(", \n")}
]
#{API_SEPARATOR}

RUBY

QUERY_FILE = "query.rb"
query = File.read(QUERY_FILE)
query = ruby_apis + query.gsub(/#{API_SEPARATOR}.+#{API_SEPARATOR}\n*/m, "")
File.write(QUERY_FILE, query)
